services:
  database:
    container_name: "postgres_db"
    image: "postgres:16.2-alpine3.19"
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=homie
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local
