[workspace]
members = [
    "homie-api", "homie-core",
    "homie-data", "homie-webapp", "db-test"
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true # Same as strip = symbols
