[workspace]
members = [
    "homie-api", "homie-core",
    "homie-data", "homie-webapp",
    "sqlx-poc",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true # Same as strip = symbols

[profile.release.package.homie-webapp]
inherits = "release"
opt-level = 'z'
