[config]
default_to_workspace = false

# Tasks
[tasks.format]
command = "cargo"
toolchain = "nightly"
args = [
    "fmt",
]

[tasks.clippy]
command = "cargo"
args = [
    "clippy",
]

[tasks.test]
dependencies = ["format"]
command = "cargo"
args = [
    "test",
    "--",
    "--nocapture",
]

[tasks.local]
command = "sh"
args = [
    "local/run.sh",
]

# Shortcuts
[tasks.t]
alias = "test"

[tasks.l]
alias = "local"

[tasks.cf]
dependencies = ["clippy", "format"]
