[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = [
  "build",
  "--bins",
  "--release",
  "--locked",
]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = [
  "fmt",
]

[tasks.test]
command = "cargo"
args = [
  "test",
  "--",
  "--nocapture",
]

[tasks.bb]
alias = "build"

[tasks.t]
alias = "test"

[tasks.f]
alias = "format"
