[config]
default_to_workspace = false

[tasks.build]
dependencies = ["format"]
command = "cargo"
args = [
    "build",
    "--bins",
    "--release",
    "--locked",
]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = [
    "fmt",
]

[tasks.clippy]
command = "cargo"
args = [
    "clippy",
]

[tasks.test]
dependencies = ["format"]
command = "cargo"
args = [
    "test",
    "--",
    "--nocapture",
]

[tasks.local]
command = "sh"
args = [
    "local_dev/run.sh",
]

[tasks.b]
alias = "build"

[tasks.t]
alias = "test"

[tasks.c]
alias = "clippy"

[tasks.f]
alias = "format"

[tasks.l]
alias = "local"
