[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = [
  "build",
  "--bins",
  "--release",
  "--locked",
]

[tasks.test]
command = "cargo"
args = [
  "test",
]

[tasks.bb]
alias = "build"

[tasks.t]
alias = "test"

