[config]
default_to_workspace = false

[tasks.build]
dependencies = ["format"]
command = "cargo"
args = [
    "build",
    "--release",
    "--locked",
]

[tasks.test]
command = "cargo"
args = [
    "test",
    "--",
    "--nocapture",
]

[tasks.b]
alias = "build"

[tasks.t]
alias = "test"
