[package]
name = "homie-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }

[dependencies.sqlx]
optional = true
version = "0.8.2"
features = ["postgres", "runtime-tokio", "tls-rustls", "chrono", "macros"]

[dependencies.utoipa]
optional = true
version = "4.2.3"
default-features = false
features = ["axum_extras"]

[dependencies.utoipa-swagger-ui]
optional = true
version = "7.1.0"

[dependencies.serde-wasm-bindgen]
optional = true
version = "0.6"

[features]
default = ["db", "docs"]

db = ["sqlx"]
docs = ["utoipa", "utoipa-swagger-ui"]
wasm = ["serde-wasm-bindgen"]
