[config]
default_to_workspace = false

[tasks.run]
command = "cargo"
args = [
  "run",
]

[tasks.test]
command = "cargo"
args = [
  "test",
  "--",
  "--nocapture",
]

[tasks.r]
alias = "run"

[tasks.t]
alias = "test"
